/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexionBDD.Conexion;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mathcrap
 */
public class FacturasProveedor extends javax.swing.JFrame {

    Conexion conn;
    String cliente, anio;
    JTable auxP;
    public FacturasProveedor(Conexion conn, String cliente, String anio) {
        initComponents();
        this.setSize(1000, 400);
        this.conn = conn;
        this.anio = anio;
        this.cliente = cliente;
        
        this.jLabel1.setText(this.jLabel1.getText() + " " + this.cliente);
        this.jLabel2.setText(this.jLabel2.getText() + " " + this.anio);
        
        String consulta = "SELECT e.id_establecimiento as ruc\n" +
",e.nombre_establecimiento AS establecimiento\n" +
",count(e.id_establecimiento) as cantidad\n" +
",cast((select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Alimentacion'\n" +
")as numeric) as alimentacion,cast(\n" +
"(select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Educacion'\n" +
")as numeric) as educacion,cast(\n" +
"(select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Salud'\n" +
")as numeric) as salud,cast(\n" +
"(select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Vestimenta'\n" +
")as numeric) as vestimenta,cast(\n" +
"(select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Vivienda'\n" +
")as numeric) as vivienda,cast(\n" +
"(select total from tipo_gasto t where id_factura=f.id_factura\n" +
"and tipo='Otro'\n" +
")as numeric) as otro\n" +
"from factura f, establecimiento e, cliente c\n" +
"where f.tipo_factura='Personal'\n" +
"and f.id_establecimiento=e.id_establecimiento\n" +
"and f.id_cliente=c.id_cliente\n" +
"and f.fecha_emision>= strftime('%d/%m/%Y','" + this.anio + "-01-01')\n" +
"and f.fecha_emision<strftime('%d/%m/%Y','" + this.anio + "-12-31')\n" +
"and c.id_cliente='" + this.cliente +"'\n" +
"group by e.id_establecimiento";
        System.out.println(consulta);
        ArrayList elementos = conn.ddl(consulta);
        
        // Llenado de tabla
        int contador = 0;
        Object[] datos = new Object[9];

        for (Object elemento : elementos) { // todos los elementos de la consulta
            datos[contador] = elemento.toString();

            contador++;
            if(contador >= 9){
                contador = 0;
                agregarDatosTabla(datos);
            }
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProveedor = new javax.swing.JTable();
        jbtSalir = new javax.swing.JButton();
        jbtPDF = new javax.swing.JButton();
        jbtExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FACTURAS POR PROVEEDOR PARA");

        jLabel2.setText("AÑO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jtbProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "NOMBRE", "CANTIDAD", "ALIMENTACION", "VIVIENDA", "VESTIDO", "SALUD", "EDUCACION", "OTROS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbProveedor);
        if (jtbProveedor.getColumnModel().getColumnCount() > 0) {
            jtbProveedor.getColumnModel().getColumn(0).setHeaderValue("RUC");
            jtbProveedor.getColumnModel().getColumn(1).setHeaderValue("NOMBRE");
            jtbProveedor.getColumnModel().getColumn(2).setHeaderValue("CANTIDAD");
            jtbProveedor.getColumnModel().getColumn(3).setHeaderValue("ALIMENTACION");
            jtbProveedor.getColumnModel().getColumn(4).setHeaderValue("VIVIENDA");
            jtbProveedor.getColumnModel().getColumn(5).setHeaderValue("VESTIDO");
            jtbProveedor.getColumnModel().getColumn(6).setHeaderValue("SALUD");
            jtbProveedor.getColumnModel().getColumn(7).setHeaderValue("EDUCACION");
            jtbProveedor.getColumnModel().getColumn(8).setHeaderValue("OTROS");
        }

        jbtSalir.setText("SALIR");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jbtPDF.setText("PDF");
        jbtPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPDFActionPerformed(evt);
            }
        });

        jbtExcel.setText("EXCEL");
        jbtExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcel)
                        .addGap(542, 542, 542)
                        .addComponent(jbtSalir)
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalir)
                    .addComponent(jbtPDF)
                    .addComponent(jbtExcel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jbtPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPDFActionPerformed
        exportarPDF();
    }//GEN-LAST:event_jbtPDFActionPerformed

    private void jbtExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcelActionPerformed
        exportarExcel();
    }//GEN-LAST:event_jbtExcelActionPerformed

    
    private void exportarExcel(){
        auxP = jtbProveedor;
        
        String file = JOptionPane.showInputDialog(null, "Ingrese el Nombre del archivo");
        String path = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        if (auxP != null) {
            toExcel(auxP, new File(path + "/" + file + "-Personal.xls"));
        }
        JOptionPane.showMessageDialog(null, "Reportes exportados exitosamente");
        
    }
    
    public void toExcel(JTable table, File file) {
        try {
            TableModel model = table.getModel();
            FileWriter excel = new FileWriter(file);

            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i) + "\t");
            }

            excel.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString() + "\t");
                }
                excel.write("\n");
            }

            excel.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void exportarPDF(){
        
    }
    
    private void agregarDatosTabla(Object[] datos){
        DefaultTableModel tabla = (DefaultTableModel)jtbProveedor.getModel();
        tabla.addRow(datos);

    }
    
    private void limpiarTabla(){
        DefaultTableModel tabla = (DefaultTableModel)jtbProveedor.getModel();
        while( tabla.getRowCount() > 0){
            tabla.removeRow(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Conexion nueva = new Conexion();
                
                new FacturasProveedor(nueva, "1234567897", "2015").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtExcel;
    private javax.swing.JButton jbtPDF;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JTable jtbProveedor;
    // End of variables declaration//GEN-END:variables
}
