/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.libres.aplicacioneslibres.interfaces;

import com.libres.aplicacioneslibres.aplicacioneslibres.Reporte;
import com.libres.aplicacioneslibres.conexionbdd.Conexion;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mathcrap
 */
public class FacturaClienteNegocio extends javax.swing.JFrame {

    /**
     * Creates new form FacturaClienteNegocio
     */
    private Conexion conn;
    private String anio;
    private String cliente;
    private Reporte reporte;
    
    public FacturaClienteNegocio(Conexion conn, String anio, String cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.conn = conn;
        this.anio = anio;
        this.cliente = cliente;
        
        this.jLabel1.setText(this.jLabel1.getText() + " " + this.cliente);
        this.jLabel2.setText(this.jLabel2.getText() + " " + this.anio);
        this.reporte = new Reporte(conn);
        
        String consulta = "SELECT  f.id_factura as id\n" +
",e.id_establecimiento as ruc\n" +
",e.nombre_establecimiento AS establecimiento\n" +
",cast(total_sin_iva as numeric) AS total_sin_iva\n" +
",cast(iva as numeric) AS iva\n" +
",cast(total_con_iva as numeric) AS total_con_iva\n" +
"from factura f, establecimiento e, cliente c\n" +
"where f.tipo_factura='Negocio'\n" +
"and f.id_establecimiento=e.id_establecimiento\n" +
"and f.id_cliente=c.id_cliente\n" +
"and f.fecha_emision>= strftime('%d/%m/%Y','"+this.anio+"-01-01')\n" +
"and f.fecha_emision<strftime('%d/%m/%Y','"+this.anio+"-12-31')\n" +
"and c.id_cliente='" + this.cliente + "'";
        System.out.println(consulta);
        ArrayList elementos = conn.ddl(consulta);
        
        // Llenado de tabla
        int contador = 0;
        Object[] datos = new Object[6];

        for (Object elemento : elementos) { // todos los elementos de la consulta
            datos[contador] = elemento.toString();

            contador++;
            if(contador >= 6){
                contador = 0;
                agregarDatosTabla(datos);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("REPORTE DE FACTURA PARA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "RUC", "NOMBRE", "TOTAL SIN IVA", "IVA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("FACTURA PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("FACTURA EXCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Factura como pdf
        HashMap parametros = new HashMap();
        int fila = this.jTable1.getSelectedRow();
        if(fila >= 0){
            String factura = this.jTable1.getValueAt(fila, 0).toString();
            parametros.put("codeInvoice", factura);
            this.reporte.generar_reporte("reporteDetallePorFactura", parametros);
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una factura");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // factura como excel
        HashMap parametros = new HashMap();
        int fila = this.jTable1.getSelectedRow();
        if(fila >= 0){
            String factura = this.jTable1.getValueAt(fila, 0).toString();
            parametros.put("codeInvoice", factura);
            this.reporte.generar_excel("reporteDetallePorFactura", parametros);
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una factura");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agregarDatosTabla(Object[] datos){
        DefaultTableModel tabla = (DefaultTableModel)jTable1.getModel();
        tabla.addRow(datos);

    }
    
    private void limpiarTabla(){
        DefaultTableModel tabla = (DefaultTableModel)jTable1.getModel();
        while( tabla.getRowCount() > 0){
            tabla.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaClienteNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaClienteNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaClienteNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaClienteNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FacturaClienteNegocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
